### ISSUE TITLE
When benchmarking (either CPU or GPU) no ethminer output is displayed

### ISSUE THREAD

**Issue by jbaldwinroberts** [CameronDiver/RunEthereumMiner#2]
joseph@joe-ubuntu:~/git/RunEthereumMiner$ python runminer.py -M -s --geth="../go-ethereum/build/bin/geth" --ethminer="/usr/bin/ethminer"
[22:28  info]   Running command '../go-ethereum/build/bin/geth --rpccorsdomain localhost --rpc'
[22:28  info]   Running command '/usr/bin/ethminer -M'

**Comment by CameronDiver** [comment]
Sorted it out now. Added that the verbose flag is set automatically on a benchmark, and changed it to read from the stdout stream when benchmarking because that's where ethminer puts the output.
