### ISSUE TITLE
Geth Logging

### ISSUE THREAD

**Issue by CameronDiver** [CameronDiver/RunEthereumMiner#9]
Currently Geth only reports on 2 kinds of lines, this needs to be increased as more information can be received from geth.

**Comment by jbaldwinroberts** [comment]
Added logging for protocol, block chain version and server init.

Still want to add logging for lost connection, mined block, total number of mined blocks.

**Comment by CameronDiver** [comment]
Sounds good, other than that everything of use can be retrieved with json
